// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { assembly, assemblySequences, gene, geneSearch, health, jbrowseChromSizes, jbrowseConfig, jbrowseDefaultConfig, jbrowseFeatures, type Options, refgetSequence, refgetServiceInfo, regionFeatures, taxon } from '../sdk.gen';
import type { AssemblyData, AssemblyError, AssemblyResponse, AssemblySequencesData, AssemblySequencesError, AssemblySequencesResponse, GeneData, GeneError, GeneResponse, GeneSearchData, GeneSearchResponse, HealthData, HealthResponse2, JbrowseChromSizesData, JbrowseChromSizesError, JbrowseChromSizesResponse, JbrowseConfigData, JbrowseConfigError, JbrowseConfigResponse, JbrowseDefaultConfigData, JbrowseDefaultConfigError, JbrowseDefaultConfigResponse, JbrowseFeaturesData, JbrowseFeaturesError, JbrowseFeaturesResponse, RefgetSequenceData, RefgetSequenceError, RefgetSequenceResponse, RefgetServiceInfoData, RefgetServiceInfoResponse, RegionFeaturesData, RegionFeaturesError, RegionFeaturesResponse, TaxonData, TaxonError, TaxonResponse2 } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const healthQueryKey = (options?: Options<HealthData>) => createQueryKey('health', options);

export const healthOptions = (options?: Options<HealthData>) => queryOptions<HealthResponse2, DefaultError, HealthResponse2, ReturnType<typeof healthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await health({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthQueryKey(options)
});

export const jbrowseChromSizesQueryKey = (options: Options<JbrowseChromSizesData>) => createQueryKey('jbrowseChromSizes', options);

export const jbrowseChromSizesOptions = (options: Options<JbrowseChromSizesData>) => queryOptions<JbrowseChromSizesResponse, JbrowseChromSizesError, JbrowseChromSizesResponse, ReturnType<typeof jbrowseChromSizesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await jbrowseChromSizes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: jbrowseChromSizesQueryKey(options)
});

export const jbrowseFeaturesQueryKey = (options: Options<JbrowseFeaturesData>) => createQueryKey('jbrowseFeatures', options);

export const jbrowseFeaturesOptions = (options: Options<JbrowseFeaturesData>) => queryOptions<JbrowseFeaturesResponse, JbrowseFeaturesError, JbrowseFeaturesResponse, ReturnType<typeof jbrowseFeaturesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await jbrowseFeatures({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: jbrowseFeaturesQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const jbrowseFeaturesInfiniteQueryKey = (options: Options<JbrowseFeaturesData>): QueryKey<Options<JbrowseFeaturesData>> => createQueryKey('jbrowseFeatures', options, true);

export const jbrowseFeaturesInfiniteOptions = (options: Options<JbrowseFeaturesData>) => infiniteQueryOptions<JbrowseFeaturesResponse, JbrowseFeaturesError, InfiniteData<JbrowseFeaturesResponse>, QueryKey<Options<JbrowseFeaturesData>>, number | Pick<QueryKey<Options<JbrowseFeaturesData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<JbrowseFeaturesData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                start: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await jbrowseFeatures({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: jbrowseFeaturesInfiniteQueryKey(options)
});

export const jbrowseDefaultConfigQueryKey = (options?: Options<JbrowseDefaultConfigData>) => createQueryKey('jbrowseDefaultConfig', options);

export const jbrowseDefaultConfigOptions = (options?: Options<JbrowseDefaultConfigData>) => queryOptions<JbrowseDefaultConfigResponse, JbrowseDefaultConfigError, JbrowseDefaultConfigResponse, ReturnType<typeof jbrowseDefaultConfigQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await jbrowseDefaultConfig({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: jbrowseDefaultConfigQueryKey(options)
});

export const jbrowseConfigQueryKey = (options: Options<JbrowseConfigData>) => createQueryKey('jbrowseConfig', options);

export const jbrowseConfigOptions = (options: Options<JbrowseConfigData>) => queryOptions<JbrowseConfigResponse, JbrowseConfigError, JbrowseConfigResponse, ReturnType<typeof jbrowseConfigQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await jbrowseConfig({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: jbrowseConfigQueryKey(options)
});

export const refgetServiceInfoQueryKey = (options?: Options<RefgetServiceInfoData>) => createQueryKey('refgetServiceInfo', options);

export const refgetServiceInfoOptions = (options?: Options<RefgetServiceInfoData>) => queryOptions<RefgetServiceInfoResponse, DefaultError, RefgetServiceInfoResponse, ReturnType<typeof refgetServiceInfoQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await refgetServiceInfo({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: refgetServiceInfoQueryKey(options)
});

export const refgetSequenceQueryKey = (options: Options<RefgetSequenceData>) => createQueryKey('refgetSequence', options);

export const refgetSequenceOptions = (options: Options<RefgetSequenceData>) => queryOptions<RefgetSequenceResponse, RefgetSequenceError, RefgetSequenceResponse, ReturnType<typeof refgetSequenceQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await refgetSequence({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: refgetSequenceQueryKey(options)
});

export const refgetSequenceInfiniteQueryKey = (options: Options<RefgetSequenceData>): QueryKey<Options<RefgetSequenceData>> => createQueryKey('refgetSequence', options, true);

export const refgetSequenceInfiniteOptions = (options: Options<RefgetSequenceData>) => infiniteQueryOptions<RefgetSequenceResponse, RefgetSequenceError, InfiniteData<RefgetSequenceResponse>, QueryKey<Options<RefgetSequenceData>>, number | null | Pick<QueryKey<Options<RefgetSequenceData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<RefgetSequenceData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                start: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await refgetSequence({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: refgetSequenceInfiniteQueryKey(options)
});

export const geneQueryKey = (options: Options<GeneData>) => createQueryKey('gene', options);

export const geneOptions = (options: Options<GeneData>) => queryOptions<GeneResponse, GeneError, GeneResponse, ReturnType<typeof geneQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await gene({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: geneQueryKey(options)
});

export const geneSearchQueryKey = (options?: Options<GeneSearchData>) => createQueryKey('geneSearch', options);

export const geneSearchOptions = (options?: Options<GeneSearchData>) => queryOptions<GeneSearchResponse, DefaultError, GeneSearchResponse, ReturnType<typeof geneSearchQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await geneSearch({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: geneSearchQueryKey(options)
});

export const assemblyQueryKey = (options: Options<AssemblyData>) => createQueryKey('assembly', options);

export const assemblyOptions = (options: Options<AssemblyData>) => queryOptions<AssemblyResponse, AssemblyError, AssemblyResponse, ReturnType<typeof assemblyQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await assembly({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: assemblyQueryKey(options)
});

export const regionFeaturesQueryKey = (options: Options<RegionFeaturesData>) => createQueryKey('regionFeatures', options);

export const regionFeaturesOptions = (options: Options<RegionFeaturesData>) => queryOptions<RegionFeaturesResponse, RegionFeaturesError, RegionFeaturesResponse, ReturnType<typeof regionFeaturesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await regionFeatures({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: regionFeaturesQueryKey(options)
});

export const assemblySequencesQueryKey = (options: Options<AssemblySequencesData>) => createQueryKey('assemblySequences', options);

export const assemblySequencesOptions = (options: Options<AssemblySequencesData>) => queryOptions<AssemblySequencesResponse, AssemblySequencesError, AssemblySequencesResponse, ReturnType<typeof assemblySequencesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await assemblySequences({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: assemblySequencesQueryKey(options)
});

export const taxonQueryKey = (options: Options<TaxonData>) => createQueryKey('taxon', options);

export const taxonOptions = (options: Options<TaxonData>) => queryOptions<TaxonResponse2, TaxonError, TaxonResponse2, ReturnType<typeof taxonQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await taxon({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: taxonQueryKey(options)
});
