[package]
name = "worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
genome-domain = { path = "../../crates/genome/domain", version = "0.1.0" }
genome-service = { path = "../../crates/genome/service", version = "0.1.0" }
genome-store = { path = "../../crates/genome/store", version = "0.1.0" }
rmp-serde.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
