[package]
name = "worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
genome-core = { path = "../../crates/genome-core", version = "0.1.0" }
rmp-serde.workspace = true
serde.workspace = true
serde_json.workspace = true
service = { path = "../../crates/service", version = "0.1.0" }
storage = { path = "../../crates/storage", version = "0.1.0" }
thiserror.workspace = true

[lints]
workspace = true
