[package]
name = "epigenome-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
epigenome-domain = { path = "../domain", version = "0.1.0" }
expression-domain = { path = "../../expression/domain", version = "0.1.0" }
flate2.workspace = true
genome-domain = { path = "../../genome/domain", version = "0.1.0" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
toml = "0.9"

[dev-dependencies]
rstest.workspace = true
tempfile = "3"

[lints]
workspace = true
