[package]
name = "portal-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
epigenome-core = { path = "../../crates/epigenome-core", version = "0.1.0" }
epigenome-store = { path = "../../crates/epigenome-store", version = "0.1.0" }
flate2.workspace = true
genome-core = { path = "../../crates/genome-core", version = "0.1.0" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
storage = { path = "../../crates/storage", version = "0.1.0" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
