[package]
name = "portal-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
epigenome-domain = { path = "../../crates/epigenome/domain", version = "0.1.0" }
epigenome-store = { path = "../../crates/epigenome/store", version = "0.1.0" }
flate2.workspace = true
genome-domain = { path = "../../crates/genome/domain", version = "0.1.0" }
genome-store = { path = "../../crates/genome/store", version = "0.1.0" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
