[package]
name = "api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
clap.workspace = true
co-expression = { path = "../../crates/expression/coexpression", version = "0.1.0" }
enrichment-core = { path = "../../crates/enrichment/domain", version = "0.1.0" }
epigenome-domain = { path = "../../crates/epigenome/domain", version = "0.1.0" }
epigenome-store = { path = "../../crates/epigenome/store", version = "0.1.0" }
expression-domain = { path = "../../crates/expression/domain", version = "0.1.0" }
expression-store = { path = "../../crates/expression/store", version = "0.1.0" }
genome-domain = { path = "../../crates/genome/domain", version = "0.1.0" }
genome-service = { path = "../../crates/genome/service", version = "0.1.0" }
genome-store = { path = "../../crates/genome/store", version = "0.1.0" }
rmp-serde.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower-http = { workspace = true, features = ["cors", "fs"] }
tracing.workspace = true
tracing-subscriber.workspace = true
utoipa.workspace = true

[lints]
workspace = true
