[package]
name = "expression-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
genome-core = { path = "../genome-core", version = "0.1.0" }
serde.workspace = true
thiserror.workspace = true
utoipa.workspace = true

[dev-dependencies]
rstest.workspace = true

[lints]
workspace = true
