// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AssemblyData, AssemblyErrors, AssemblyResponses, AssemblySequencesData, AssemblySequencesErrors, AssemblySequencesResponses, BlastnJobData, BlastnJobErrors, BlastnJobResponses, CreateBlastnJobData, CreateBlastnJobErrors, CreateBlastnJobResponses, GeneData, GeneErrors, GeneExpressionData, GeneExpressionErrors, GeneExpressionResponses, GeneResponses, GeneSearchData, GeneSearchResponses, HealthData, HealthResponses, JbrowseChromSizesData, JbrowseChromSizesErrors, JbrowseChromSizesResponses, JbrowseConfigData, JbrowseConfigErrors, JbrowseConfigResponses, JbrowseDefaultConfigData, JbrowseDefaultConfigErrors, JbrowseDefaultConfigResponses, JbrowseFeaturesData, JbrowseFeaturesErrors, JbrowseFeaturesResponses, RefgetSequenceData, RefgetSequenceErrors, RefgetSequenceResponses, RefgetServiceInfoData, RefgetServiceInfoResponses, RegionFeaturesData, RegionFeaturesErrors, RegionFeaturesResponses, SequenceSegmentsData, SequenceSegmentsErrors, SequenceSegmentsResponses, TaxonData, TaxonErrors, TaxonResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const health = <ThrowOnError extends boolean = true>(options?: Options<HealthData, ThrowOnError>) => (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

export const jbrowseChromSizes = <ThrowOnError extends boolean = true>(options: Options<JbrowseChromSizesData, ThrowOnError>) => (options.client ?? client).get<JbrowseChromSizesResponses, JbrowseChromSizesErrors, ThrowOnError>({ url: '/jbrowse/assemblies/{accession}/chrom.sizes', ...options });

export const jbrowseFeatures = <ThrowOnError extends boolean = true>(options: Options<JbrowseFeaturesData, ThrowOnError>) => (options.client ?? client).get<JbrowseFeaturesResponses, JbrowseFeaturesErrors, ThrowOnError>({ url: '/jbrowse/assemblies/{accession}/features', ...options });

export const jbrowseDefaultConfig = <ThrowOnError extends boolean = true>(options?: Options<JbrowseDefaultConfigData, ThrowOnError>) => (options?.client ?? client).get<JbrowseDefaultConfigResponses, JbrowseDefaultConfigErrors, ThrowOnError>({ url: '/jbrowse/config', ...options });

export const jbrowseConfig = <ThrowOnError extends boolean = true>(options: Options<JbrowseConfigData, ThrowOnError>) => (options.client ?? client).get<JbrowseConfigResponses, JbrowseConfigErrors, ThrowOnError>({ url: '/jbrowse/config/{accession}', ...options });

export const refgetServiceInfo = <ThrowOnError extends boolean = true>(options?: Options<RefgetServiceInfoData, ThrowOnError>) => (options?.client ?? client).get<RefgetServiceInfoResponses, unknown, ThrowOnError>({ url: '/sequence/service-info', ...options });

export const refgetSequence = <ThrowOnError extends boolean = true>(options: Options<RefgetSequenceData, ThrowOnError>) => (options.client ?? client).get<RefgetSequenceResponses, RefgetSequenceErrors, ThrowOnError>({ url: '/sequence/{checksum}', ...options });

export const gene = <ThrowOnError extends boolean = true>(options: Options<GeneData, ThrowOnError>) => (options.client ?? client).get<GeneResponses, GeneErrors, ThrowOnError>({ url: '/v2/gene/id/{gene_id}', ...options });

export const geneExpression = <ThrowOnError extends boolean = true>(options: Options<GeneExpressionData, ThrowOnError>) => (options.client ?? client).get<GeneExpressionResponses, GeneExpressionErrors, ThrowOnError>({ url: '/v2/gene/id/{gene_id}/expression', ...options });

export const geneSearch = <ThrowOnError extends boolean = true>(options?: Options<GeneSearchData, ThrowOnError>) => (options?.client ?? client).get<GeneSearchResponses, unknown, ThrowOnError>({ url: '/v2/gene/search', ...options });

export const assembly = <ThrowOnError extends boolean = true>(options: Options<AssemblyData, ThrowOnError>) => (options.client ?? client).get<AssemblyResponses, AssemblyErrors, ThrowOnError>({ url: '/v2/genome/accession/{accession}', ...options });

export const regionFeatures = <ThrowOnError extends boolean = true>(options: Options<RegionFeaturesData, ThrowOnError>) => (options.client ?? client).get<RegionFeaturesResponses, RegionFeaturesErrors, ThrowOnError>({ url: '/v2/genome/accession/{accession}/region/{region}/features', ...options });

export const sequenceSegments = <ThrowOnError extends boolean = true>(options: Options<SequenceSegmentsData, ThrowOnError>) => (options.client ?? client).get<SequenceSegmentsResponses, SequenceSegmentsErrors, ThrowOnError>({ url: '/v2/genome/accession/{accession}/sequence/{sequence_name}', ...options });

export const assemblySequences = <ThrowOnError extends boolean = true>(options: Options<AssemblySequencesData, ThrowOnError>) => (options.client ?? client).get<AssemblySequencesResponses, AssemblySequencesErrors, ThrowOnError>({ url: '/v2/genome/accession/{accession}/sequences', ...options });

export const taxon = <ThrowOnError extends boolean = true>(options: Options<TaxonData, ThrowOnError>) => (options.client ?? client).get<TaxonResponses, TaxonErrors, ThrowOnError>({ url: '/v2/genome/taxon/{tax_id}', ...options });

export const createBlastnJob = <ThrowOnError extends boolean = true>(options: Options<CreateBlastnJobData, ThrowOnError>) => (options.client ?? client).post<CreateBlastnJobResponses, CreateBlastnJobErrors, ThrowOnError>({
    url: '/v2/tools/blastn/jobs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const blastnJob = <ThrowOnError extends boolean = true>(options: Options<BlastnJobData, ThrowOnError>) => (options.client ?? client).get<BlastnJobResponses, BlastnJobErrors, ThrowOnError>({ url: '/v2/tools/blastn/jobs/{job_id}', ...options });
