// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AssemblyData, AssemblyErrors, AssemblyResponses, AssemblySequencesData, AssemblySequencesErrors, AssemblySequencesResponses, BlastnJobData, BlastnJobErrors, BlastnJobResponses, BlastpJobData, BlastpJobErrors, BlastpJobResponses, CreateBlastnJobData, CreateBlastnJobErrors, CreateBlastnJobResponses, CreateBlastpJobData, CreateBlastpJobErrors, CreateBlastpJobResponses, EnrichmentAnalysisData, EnrichmentAnalysisErrors, EnrichmentAnalysisResponses, ExpressionClustergramData, ExpressionClustergramErrors, ExpressionClustergramResponses, GeneData, GeneErrors, GeneExpressionData, GeneExpressionErrors, GeneExpressionResponses, GeneKeggData, GeneKeggErrors, GeneKeggResponses, GeneOrthogroupsData, GeneOrthogroupsErrors, GeneOrthogroupsResponses, GeneResponses, GeneSearchData, GeneSearchResponses, HealthData, HealthResponses, JbrowseChromSizesData, JbrowseChromSizesErrors, JbrowseChromSizesResponses, JbrowseConfigData, JbrowseConfigErrors, JbrowseConfigResponses, JbrowseDefaultConfigData, JbrowseDefaultConfigErrors, JbrowseDefaultConfigResponses, JbrowseFeaturesData, JbrowseFeaturesErrors, JbrowseFeaturesResponses, KeggPathwayData, KeggPathwayErrors, KeggPathwayResponses, KeggPathwaysData, KeggPathwaysResponses, OrthogroupData, OrthogroupErrors, OrthogroupResponses, RefgetSequenceData, RefgetSequenceErrors, RefgetSequenceResponses, RefgetServiceInfoData, RefgetServiceInfoResponses, RegionFeaturesData, RegionFeaturesErrors, RegionFeaturesResponses, SequenceSegmentsData, SequenceSegmentsErrors, SequenceSegmentsResponses, TaxonData, TaxonErrors, TaxonResponses, TranscriptProteinData, TranscriptProteinErrors, TranscriptProteinResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const health = <ThrowOnError extends boolean = true>(options?: Options<HealthData, ThrowOnError>) => (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

export const jbrowseChromSizes = <ThrowOnError extends boolean = true>(options: Options<JbrowseChromSizesData, ThrowOnError>) => (options.client ?? client).get<JbrowseChromSizesResponses, JbrowseChromSizesErrors, ThrowOnError>({ url: '/jbrowse/assemblies/{accession}/chrom.sizes', ...options });

export const jbrowseFeatures = <ThrowOnError extends boolean = true>(options: Options<JbrowseFeaturesData, ThrowOnError>) => (options.client ?? client).get<JbrowseFeaturesResponses, JbrowseFeaturesErrors, ThrowOnError>({ url: '/jbrowse/assemblies/{accession}/features', ...options });

export const jbrowseDefaultConfig = <ThrowOnError extends boolean = true>(options?: Options<JbrowseDefaultConfigData, ThrowOnError>) => (options?.client ?? client).get<JbrowseDefaultConfigResponses, JbrowseDefaultConfigErrors, ThrowOnError>({ url: '/jbrowse/config', ...options });

export const jbrowseConfig = <ThrowOnError extends boolean = true>(options: Options<JbrowseConfigData, ThrowOnError>) => (options.client ?? client).get<JbrowseConfigResponses, JbrowseConfigErrors, ThrowOnError>({ url: '/jbrowse/config/{accession}', ...options });

export const refgetServiceInfo = <ThrowOnError extends boolean = true>(options?: Options<RefgetServiceInfoData, ThrowOnError>) => (options?.client ?? client).get<RefgetServiceInfoResponses, unknown, ThrowOnError>({ url: '/sequence/service-info', ...options });

export const refgetSequence = <ThrowOnError extends boolean = true>(options: Options<RefgetSequenceData, ThrowOnError>) => (options.client ?? client).get<RefgetSequenceResponses, RefgetSequenceErrors, ThrowOnError>({ url: '/sequence/{checksum}', ...options });

export const enrichmentAnalysis = <ThrowOnError extends boolean = true>(options: Options<EnrichmentAnalysisData, ThrowOnError>) => (options.client ?? client).post<EnrichmentAnalysisResponses, EnrichmentAnalysisErrors, ThrowOnError>({
    url: '/v2/analysis/enrichment',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const expressionClustergram = <ThrowOnError extends boolean = true>(options: Options<ExpressionClustergramData, ThrowOnError>) => (options.client ?? client).get<ExpressionClustergramResponses, ExpressionClustergramErrors, ThrowOnError>({ url: '/v2/expression/clustergram', ...options });

export const gene = <ThrowOnError extends boolean = true>(options: Options<GeneData, ThrowOnError>) => (options.client ?? client).get<GeneResponses, GeneErrors, ThrowOnError>({ url: '/v2/gene/id/{gene_id}', ...options });

export const geneExpression = <ThrowOnError extends boolean = true>(options: Options<GeneExpressionData, ThrowOnError>) => (options.client ?? client).get<GeneExpressionResponses, GeneExpressionErrors, ThrowOnError>({ url: '/v2/gene/id/{gene_id}/expression', ...options });

export const geneKegg = <ThrowOnError extends boolean = true>(options: Options<GeneKeggData, ThrowOnError>) => (options.client ?? client).get<GeneKeggResponses, GeneKeggErrors, ThrowOnError>({ url: '/v2/gene/id/{gene_id}/kegg', ...options });

export const geneOrthogroups = <ThrowOnError extends boolean = true>(options: Options<GeneOrthogroupsData, ThrowOnError>) => (options.client ?? client).get<GeneOrthogroupsResponses, GeneOrthogroupsErrors, ThrowOnError>({ url: '/v2/gene/id/{gene_id}/orthogroups', ...options });

export const geneSearch = <ThrowOnError extends boolean = true>(options?: Options<GeneSearchData, ThrowOnError>) => (options?.client ?? client).get<GeneSearchResponses, unknown, ThrowOnError>({ url: '/v2/gene/search', ...options });

export const assembly = <ThrowOnError extends boolean = true>(options: Options<AssemblyData, ThrowOnError>) => (options.client ?? client).get<AssemblyResponses, AssemblyErrors, ThrowOnError>({ url: '/v2/genome/accession/{accession}', ...options });

export const regionFeatures = <ThrowOnError extends boolean = true>(options: Options<RegionFeaturesData, ThrowOnError>) => (options.client ?? client).get<RegionFeaturesResponses, RegionFeaturesErrors, ThrowOnError>({ url: '/v2/genome/accession/{accession}/region/{region}/features', ...options });

export const sequenceSegments = <ThrowOnError extends boolean = true>(options: Options<SequenceSegmentsData, ThrowOnError>) => (options.client ?? client).get<SequenceSegmentsResponses, SequenceSegmentsErrors, ThrowOnError>({ url: '/v2/genome/accession/{accession}/sequence/{sequence_name}', ...options });

export const assemblySequences = <ThrowOnError extends boolean = true>(options: Options<AssemblySequencesData, ThrowOnError>) => (options.client ?? client).get<AssemblySequencesResponses, AssemblySequencesErrors, ThrowOnError>({ url: '/v2/genome/accession/{accession}/sequences', ...options });

export const taxon = <ThrowOnError extends boolean = true>(options: Options<TaxonData, ThrowOnError>) => (options.client ?? client).get<TaxonResponses, TaxonErrors, ThrowOnError>({ url: '/v2/genome/taxon/{tax_id}', ...options });

export const keggPathway = <ThrowOnError extends boolean = true>(options: Options<KeggPathwayData, ThrowOnError>) => (options.client ?? client).get<KeggPathwayResponses, KeggPathwayErrors, ThrowOnError>({ url: '/v2/kegg/pathway/{pathway_id}', ...options });

export const keggPathways = <ThrowOnError extends boolean = true>(options?: Options<KeggPathwaysData, ThrowOnError>) => (options?.client ?? client).get<KeggPathwaysResponses, unknown, ThrowOnError>({ url: '/v2/kegg/pathways', ...options });

export const orthogroup = <ThrowOnError extends boolean = true>(options: Options<OrthogroupData, ThrowOnError>) => (options.client ?? client).get<OrthogroupResponses, OrthogroupErrors, ThrowOnError>({ url: '/v2/orthogroup/{orthogroup_id}', ...options });

export const createBlastnJob = <ThrowOnError extends boolean = true>(options: Options<CreateBlastnJobData, ThrowOnError>) => (options.client ?? client).post<CreateBlastnJobResponses, CreateBlastnJobErrors, ThrowOnError>({
    url: '/v2/tools/blastn/jobs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const blastnJob = <ThrowOnError extends boolean = true>(options: Options<BlastnJobData, ThrowOnError>) => (options.client ?? client).get<BlastnJobResponses, BlastnJobErrors, ThrowOnError>({ url: '/v2/tools/blastn/jobs/{job_id}', ...options });

export const createBlastpJob = <ThrowOnError extends boolean = true>(options: Options<CreateBlastpJobData, ThrowOnError>) => (options.client ?? client).post<CreateBlastpJobResponses, CreateBlastpJobErrors, ThrowOnError>({
    url: '/v2/tools/blastp/jobs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const blastpJob = <ThrowOnError extends boolean = true>(options: Options<BlastpJobData, ThrowOnError>) => (options.client ?? client).get<BlastpJobResponses, BlastpJobErrors, ThrowOnError>({ url: '/v2/tools/blastp/jobs/{job_id}', ...options });

export const transcriptProtein = <ThrowOnError extends boolean = true>(options: Options<TranscriptProteinData, ThrowOnError>) => (options.client ?? client).get<TranscriptProteinResponses, TranscriptProteinErrors, ThrowOnError>({ url: '/v2/transcript/id/{transcript_id}/protein', ...options });
