// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AnnotatedHomologyHitResponse = {
    hit: HomologyHit;
    overlappingGeneIds: Array<GeneId>;
};

export type AnnotatedHomologySearchResultResponse = {
    hits: Array<AnnotatedHomologyHitResponse>;
    method: HomologySearchMethod;
    task: string;
};

export type AnnotationEvidence = {
    attributes: {
        [key: string]: string;
    };
    method?: string | null;
    source: AnnotationSource;
};

export type AnnotationSource = 'inter_pro_scan' | 'go' | 'kegg' | 'manual' | {
    other: string;
};

export type Assembly = {
    accession: AssemblyAccession;
    name: string;
    refget_checksum?: string | null;
    source: AssemblySource;
    tax_id: TaxId;
};

export type AssemblyAccession = string;

export type AssemblySource = 'ncbi' | 'marpol_base' | 'tair' | 'phytozome' | 'community' | 'local';

export type BlastnJobRequest = {
    assemblyAccession: string;
    evalue?: number | null;
    maxTargetSeqs?: number | null;
    query: string;
    task?: string | null;
};

export type BlastnJobResponse = {
    error?: string | null;
    id: string;
    kind: string;
    result?: null | AnnotatedHomologySearchResultResponse;
    status: JobStatusResponse;
};

export type BlastpJobRequest = {
    assemblyAccession: string;
    evalue?: number | null;
    maxTargetSeqs?: number | null;
    query: string;
    task?: string | null;
};

export type Cds = {
    /**
     * GFF phase: 0, 1, or 2. Number of bases to remove from the 5' end of
     * this CDS segment to reach the first complete codon.
     */
    phase?: number | null;
    region: HalfOpenRegion;
    sequence_name: SequenceName;
    strand: Strand;
    transcript_id: TranscriptId;
};

export type ClosedRegion = {
    end: Position1;
    sequence_name: SequenceName;
    start: Position1;
};

/**
 * A flat dendrogram representation suitable for JSON APIs.
 */
export type ClusterDendrogram = {
    nodes: Array<ClusterDendrogramNode>;
    root?: number | null;
};

/**
 * One node in a flat dendrogram.
 */
export type ClusterDendrogramNode = {
    distance: number;
    id: number;
    leafIndex?: number | null;
    left?: number | null;
    right?: number | null;
    size: number;
};

export type EnrichmentAnalysisRequest = {
    annotationKinds?: Array<EnrichmentAnnotationKind> | null;
    assemblyAccession: string;
    backgroundGeneIds?: Array<string> | null;
    geneIds: Array<string>;
    limit?: number | null;
    minPopulationHits?: number | null;
};

export type EnrichmentAnalysisResponse = {
    assemblyAccession: string;
    populationSize: number;
    results: Array<EnrichmentTermResult>;
    studySize: number;
    testedTerms: number;
};

export type EnrichmentAnnotationKind = 'go_term' | 'pfam' | 'inter_pro' | 'kegg' | 'kog' | 'ncbi_fam';

export type EnrichmentTerm = {
    id: string;
    kind: EnrichmentAnnotationKind;
    name?: string | null;
    namespace?: null | GoNamespace;
};

export type EnrichmentTermResult = {
    foldEnrichment?: number | null;
    pValue: number;
    populationHits: number;
    populationSize: number;
    qValue: number;
    studyGeneIds: Array<GeneId>;
    studyHits: number;
    studySize: number;
    term: EnrichmentTerm;
};

export type ErrorResponse = {
    error: string;
};

export type Exon = {
    region: HalfOpenRegion;
    sequence_name: SequenceName;
    strand: Strand;
    transcript_id: TranscriptId;
};

export type ExpressionClustergramQuery = {
    assemblyAccession: string;
    dropMissingGenes?: boolean | null;
    geneIds: string;
    limit?: number | null;
    runs?: string | null;
    unit?: null | ExpressionUnit;
};

export type ExpressionClustergramResponse = {
    assemblyAccession: string;
    columnDendrogram: ClusterDendrogram;
    columnOrder: Array<number>;
    genes: Array<ExpressionGeneLabel>;
    rowDendrogram: ClusterDendrogram;
    rowOrder: Array<number>;
    samples: Array<ExpressionSampleLabel>;
    unit: ExpressionUnit;
    values: Array<number>;
    zScores: Array<number>;
};

export type ExpressionGeneLabel = {
    geneId: string;
    label: string;
};

export type ExpressionSampleLabel = {
    label: string;
    primaryGroup?: string | null;
    run: string;
};

/**
 * Unit in which an expression value is reported.
 *
 * The variants cover the common normalized and count-based units used by
 * downstream pipelines (Salmon, Kallisto, featureCounts, DESeq2, edgeR, ...).
 */
export type ExpressionUnit = 'tpm' | 'fpkm' | 'rpkm' | 'cpm' | 'raw_count' | 'normalized_count';

export type FunctionalAnnotation = (InterProAnnotation & {
    kind: 'inter_pro';
}) | (PfamAnnotation & {
    kind: 'pfam';
}) | (NcbiFamAnnotation & {
    kind: 'ncbi_fam';
}) | (KogAnnotation & {
    kind: 'kog';
}) | (GoTermAnnotation & {
    kind: 'go_term';
}) | (KeggAnnotation & {
    kind: 'kegg';
});

export type Gene = {
    annotations: Array<FunctionalAnnotation>;
    assembly_accession: AssemblyAccession;
    attributes: {
        [key: string]: string;
    };
    feature_type: string;
    id: GeneId;
    locus_tag?: string | null;
    region: HalfOpenRegion;
    sequence_name: SequenceName;
    strand: Strand;
    symbol?: string | null;
};

export type GeneExpressionPoint = {
    geneId: string;
    label: string;
    primaryGroup?: string | null;
    run: string;
    unit: ExpressionUnit;
    value: number;
};

export type GeneExpressionQuery = {
    limit?: number | null;
    unit?: null | ExpressionUnit;
};

export type GeneId = string;

export type GeneKeggOrthologyEntry = {
    ko: KeggEntryId;
    modules: Array<KeggModule>;
    name?: string | null;
    pathways: Array<KeggPathway>;
    reactions: Array<KeggReaction>;
};

export type GeneKeggView = {
    entries: Array<GeneKeggOrthologyEntry>;
    gene_id: GeneId;
};

export type GeneRecord = {
    cdss: Array<Cds>;
    exons: Array<Exon>;
    gene: Gene;
    transcripts: Array<Transcript>;
};

export type GeneSearchQuery = {
    limit?: number | null;
    locus_tag?: string | null;
    q?: string | null;
    symbol?: string | null;
    tax_id?: number | null;
};

export type GoNamespace = 'biological_process' | 'molecular_function' | 'cellular_component';

export type GoTermAnnotation = {
    evidence: AnnotationEvidence;
    name?: string | null;
    namespace?: null | GoNamespace;
    term_id: GoTermId;
};

export type GoTermId = string;

export type HalfOpenRegion = {
    end: Position0;
    sequence_name: SequenceName;
    start: Position0;
};

export type HealthResponse = {
    ok: boolean;
};

export type HomologyHit = {
    alignmentLength: number;
    assemblyAccession: AssemblyAccession;
    bitScore: number;
    evalue: number;
    gapOpens: number;
    mismatches: number;
    percentIdentity: number;
    queryAlignment: string;
    queryEnd: Position1;
    queryId: string;
    queryStart: Position1;
    sequenceName: SequenceName;
    strand: Strand;
    subjectAlignment: string;
    subjectEnd: Position1;
    subjectRegion: ClosedRegion;
    subjectStart: Position1;
};

export type HomologySearchMethod = 'blastn' | 'blastp';

export type InterProAnnotation = {
    evidence: AnnotationEvidence;
    interpro_id: InterProId;
    name?: string | null;
};

export type InterProId = string;

export type JBrowseAssembly = {
    aliases: Array<string>;
    name: string;
    sequence: JBrowseSequenceTrack;
};

export type JBrowseChromSizesAdapter = {
    chromSizesLocation: JBrowseUriLocation;
    type: string;
};

export type JBrowseConfigQuery = {
    base_url?: string | null;
};

export type JBrowseDefaultSession = {
    name: string;
    view: JBrowseDefaultView;
};

export type JBrowseDefaultView = {
    id: string;
    init: JBrowseDefaultViewInit;
    type: string;
};

export type JBrowseDefaultViewInit = {
    assembly: string;
    loc: string;
    tracks: Array<string>;
};

export type JBrowseFeature = {
    attributes: {
        [key: string]: string;
    };
    end: number;
    name: string;
    refName: string;
    start: number;
    strand: number;
    type: string;
    uniqueId: string;
};

export type JBrowseFeaturesQuery = {
    end: number;
    ref_name: string;
    start: number;
};

export type JBrowsePortalConfig = {
    assemblyAccession: string;
    chromSizesUrl: string;
    featuresUrl: string;
    featuresUrlTemplate: string;
    sequenceUrlTemplate: string;
};

export type JBrowseRendering = {
    type: string;
};

export type JBrowseRootConfig = {
    assemblies: Array<JBrowseAssembly>;
    defaultSession: JBrowseDefaultSession;
    plantGenomePortal: JBrowsePortalConfig;
    tracks: Array<JBrowseTrack>;
};

export type JBrowseSequenceTrack = {
    adapter: JBrowseChromSizesAdapter;
    rendering: JBrowseRendering;
    trackId: string;
    type: string;
};

export type JBrowseTrack = {
    [key: string]: unknown;
};

export type JBrowseUriLocation = {
    locationType: string;
    uri: string;
};

export type JobStatusResponse = 'queued' | 'running' | 'succeeded' | 'failed';

export type KeggAnnotation = {
    entry_id: KeggEntryId;
    entry_kind: KeggEntryKind;
    evidence: AnnotationEvidence;
    name?: string | null;
};

export type KeggCatalog = {
    ko_links?: Array<KeggKoLinks>;
    modules?: Array<KeggModule>;
    pathways?: Array<KeggPathway>;
    reactions?: Array<KeggReaction>;
};

export type KeggEntryId = string;

export type KeggEntryKind = 'orthology' | 'pathway' | 'module' | 'reaction' | 'compound' | 'glycan' | 'other';

export type KeggGeneSummary = {
    id: GeneId;
    locus_tag?: string | null;
    symbol?: string | null;
};

export type KeggKoLinks = {
    ko: KeggEntryId;
    modules: Array<KeggModuleId>;
    pathways: Array<KeggPathwayId>;
    reactions: Array<KeggReactionId>;
};

export type KeggModule = {
    id: KeggModuleId;
    name?: string | null;
};

export type KeggModuleId = string;

export type KeggPathway = {
    id: KeggPathwayId;
    name?: string | null;
};

export type KeggPathwayDetail = {
    kos: Array<KeggPathwayKoEntry>;
    pathway: KeggPathway;
};

export type KeggPathwayId = string;

export type KeggPathwayKoEntry = {
    genes: Array<KeggGeneSummary>;
    ko: KeggEntryId;
};

export type KeggPathwaySummary = {
    gene_count: number;
    ko_count: number;
    pathway: KeggPathway;
};

export type KeggReaction = {
    id: KeggReactionId;
    name?: string | null;
};

export type KeggReactionId = string;

export type KogAnnotation = {
    entry_id: KogEntryId;
    evidence: AnnotationEvidence;
    interpro_id?: null | InterProId;
    name?: string | null;
};

export type KogEntryId = string;

export type NcbiFamAccession = string;

export type NcbiFamAnnotation = {
    accession: NcbiFamAccession;
    evidence: AnnotationEvidence;
    interpro_id?: null | InterProId;
    name?: string | null;
};

export type Orthogroup = {
    id: OrthogroupId;
    members: Array<OrthogroupMember>;
};

export type OrthogroupCatalog = {
    groups: Array<Orthogroup>;
};

export type OrthogroupId = string;

export type OrthogroupMember = {
    assembly_accession?: null | AssemblyAccession;
    gene_id: GeneId;
    scientific_name: string;
    symbol?: string | null;
    tax_id: TaxId;
};

export type PfamAccession = string;

export type PfamAnnotation = {
    accession: PfamAccession;
    evidence: AnnotationEvidence;
    interpro_id?: null | InterProId;
    name?: string | null;
};

export type Position0 = number;

export type Position1 = number;

export type ProteinQuery = {
    format?: null | SequenceOutputFormat;
};

export type RefgetQuery = {
    end?: number | null;
    start?: number | null;
};

export type RefgetServiceInfo = {
    circular_supported: boolean;
    id: string;
    name: string;
    subsequence_limit?: number | null;
};

export type Sequence = {
    assembly_accession: AssemblyAccession;
    length: number;
    name: SequenceName;
    refget_checksum: string;
};

export type SequenceName = string;

export type SequenceOutputFormat = 'plain' | 'fasta';

export type SequenceSegmentsQuery = {
    /**
     * Segment ends, 0-based exclusive. Repeat once per segment.
     */
    end: Array<number>;
    format?: null | SequenceOutputFormat;
    /**
     * Segment starts, 0-based inclusive. Repeat once per segment.
     */
    start: Array<number>;
    strand?: null | Strand;
};

export type Strand = 'forward' | 'reverse' | 'unknown';

export type TaxId = number;

export type Taxon = {
    common_name?: string | null;
    rank: string;
    scientific_name: string;
    tax_id: TaxId;
};

export type TaxonResponse = {
    assemblies: Array<Assembly>;
    taxon: Taxon;
};

export type Transcript = {
    annotations: Array<FunctionalAnnotation>;
    attributes: {
        [key: string]: string;
    };
    feature_type: string;
    gene_id: GeneId;
    id: TranscriptId;
    /**
     * refget checksum of the translated protein sequence (24-byte SHA-512
     * truncated, URL-safe base64), when a protein FASTA was supplied at
     * snapshot build time. `None` for non-coding or pre-protein imports.
     */
    protein_checksum?: string | null;
    /**
     * Length of the protein in amino acids (excluding any stop symbol).
     */
    protein_length?: number | null;
    region: HalfOpenRegion;
    sequence_name: SequenceName;
    strand: Strand;
};

export type TranscriptId = string;

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * Health check
     */
    200: HealthResponse;
};

export type HealthResponse2 = HealthResponses[keyof HealthResponses];

export type JbrowseChromSizesData = {
    body?: never;
    path: {
        /**
         * Assembly accession
         */
        accession: string;
    };
    query?: never;
    url: '/jbrowse/assemblies/{accession}/chrom.sizes';
};

export type JbrowseChromSizesErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Assembly not found
     */
    404: ErrorResponse;
};

export type JbrowseChromSizesError = JbrowseChromSizesErrors[keyof JbrowseChromSizesErrors];

export type JbrowseChromSizesResponses = {
    /**
     * UCSC chrom.sizes compatible sequence sizes
     */
    200: string;
};

export type JbrowseChromSizesResponse = JbrowseChromSizesResponses[keyof JbrowseChromSizesResponses];

export type JbrowseFeaturesData = {
    body?: never;
    path: {
        /**
         * Assembly accession
         */
        accession: string;
    };
    query: {
        ref_name: string;
        start: number;
        end: number;
    };
    url: '/jbrowse/assemblies/{accession}/features';
};

export type JbrowseFeaturesErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Assembly not found
     */
    404: ErrorResponse;
};

export type JbrowseFeaturesError = JbrowseFeaturesErrors[keyof JbrowseFeaturesErrors];

export type JbrowseFeaturesResponses = {
    /**
     * Features for a JBrowse custom adapter
     */
    200: Array<JBrowseFeature>;
};

export type JbrowseFeaturesResponse = JbrowseFeaturesResponses[keyof JbrowseFeaturesResponses];

export type JbrowseDefaultConfigData = {
    body?: never;
    path?: never;
    query?: {
        base_url?: string | null;
    };
    url: '/jbrowse/config';
};

export type JbrowseDefaultConfigErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Assembly not found
     */
    404: ErrorResponse;
};

export type JbrowseDefaultConfigError = JbrowseDefaultConfigErrors[keyof JbrowseDefaultConfigErrors];

export type JbrowseDefaultConfigResponses = {
    /**
     * Default JBrowse launch config
     */
    200: JBrowseRootConfig;
};

export type JbrowseDefaultConfigResponse = JbrowseDefaultConfigResponses[keyof JbrowseDefaultConfigResponses];

export type JbrowseConfigData = {
    body?: never;
    path: {
        /**
         * Assembly accession
         */
        accession: string;
    };
    query?: {
        base_url?: string | null;
    };
    url: '/jbrowse/config/{accession}';
};

export type JbrowseConfigErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Assembly not found
     */
    404: ErrorResponse;
};

export type JbrowseConfigError = JbrowseConfigErrors[keyof JbrowseConfigErrors];

export type JbrowseConfigResponses = {
    /**
     * JBrowse launch config
     */
    200: JBrowseRootConfig;
};

export type JbrowseConfigResponse = JbrowseConfigResponses[keyof JbrowseConfigResponses];

export type RefgetServiceInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sequence/service-info';
};

export type RefgetServiceInfoResponses = {
    /**
     * refget service info
     */
    200: RefgetServiceInfo;
};

export type RefgetServiceInfoResponse = RefgetServiceInfoResponses[keyof RefgetServiceInfoResponses];

export type RefgetSequenceData = {
    body?: never;
    path: {
        /**
         * refget checksum
         */
        checksum: string;
    };
    query?: {
        start?: number | null;
        end?: number | null;
    };
    url: '/sequence/{checksum}';
};

export type RefgetSequenceErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Sequence not found
     */
    404: ErrorResponse;
};

export type RefgetSequenceError = RefgetSequenceErrors[keyof RefgetSequenceErrors];

export type RefgetSequenceResponses = {
    /**
     * Reference sequence
     */
    200: string;
};

export type RefgetSequenceResponse = RefgetSequenceResponses[keyof RefgetSequenceResponses];

export type EnrichmentAnalysisData = {
    body: EnrichmentAnalysisRequest;
    path?: never;
    query?: never;
    url: '/v2/analysis/enrichment';
};

export type EnrichmentAnalysisErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Assembly or gene not found
     */
    404: ErrorResponse;
};

export type EnrichmentAnalysisError = EnrichmentAnalysisErrors[keyof EnrichmentAnalysisErrors];

export type EnrichmentAnalysisResponses = {
    /**
     * Functional annotation over-representation analysis
     */
    200: EnrichmentAnalysisResponse;
};

export type EnrichmentAnalysisResponse2 = EnrichmentAnalysisResponses[keyof EnrichmentAnalysisResponses];

export type ExpressionClustergramData = {
    body?: never;
    path?: never;
    query: {
        assemblyAccession: string;
        geneIds: string;
        unit?: null | ExpressionUnit;
        runs?: string | null;
        limit?: number | null;
        dropMissingGenes?: boolean | null;
    };
    url: '/v2/expression/clustergram';
};

export type ExpressionClustergramErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
};

export type ExpressionClustergramError = ExpressionClustergramErrors[keyof ExpressionClustergramErrors];

export type ExpressionClustergramResponses = {
    /**
     * Expression matrix with Rust-computed cluster ordering
     */
    200: ExpressionClustergramResponse;
};

export type ExpressionClustergramResponse2 = ExpressionClustergramResponses[keyof ExpressionClustergramResponses];

export type GeneData = {
    body?: never;
    path: {
        /**
         * Gene identifier
         */
        gene_id: string;
    };
    query?: never;
    url: '/v2/gene/id/{gene_id}';
};

export type GeneErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Gene not found
     */
    404: ErrorResponse;
};

export type GeneError = GeneErrors[keyof GeneErrors];

export type GeneResponses = {
    /**
     * Gene detail
     */
    200: GeneRecord;
};

export type GeneResponse = GeneResponses[keyof GeneResponses];

export type GeneExpressionData = {
    body?: never;
    path: {
        /**
         * Gene identifier
         */
        gene_id: string;
    };
    query?: {
        unit?: null | ExpressionUnit;
        limit?: number | null;
    };
    url: '/v2/gene/id/{gene_id}/expression';
};

export type GeneExpressionErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Gene not found
     */
    404: ErrorResponse;
};

export type GeneExpressionError = GeneExpressionErrors[keyof GeneExpressionErrors];

export type GeneExpressionResponses = {
    /**
     * Expression values for one gene
     */
    200: Array<GeneExpressionPoint>;
};

export type GeneExpressionResponse = GeneExpressionResponses[keyof GeneExpressionResponses];

export type GeneKeggData = {
    body?: never;
    path: {
        /**
         * Gene identifier
         */
        gene_id: string;
    };
    query?: never;
    url: '/v2/gene/id/{gene_id}/kegg';
};

export type GeneKeggErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Gene not found
     */
    404: ErrorResponse;
};

export type GeneKeggError = GeneKeggErrors[keyof GeneKeggErrors];

export type GeneKeggResponses = {
    /**
     * Per-gene KEGG view with KOs hydrated by their related pathways/modules/reactions
     */
    200: GeneKeggView;
};

export type GeneKeggResponse = GeneKeggResponses[keyof GeneKeggResponses];

export type GeneOrthogroupsData = {
    body?: never;
    path: {
        /**
         * Gene identifier
         */
        gene_id: string;
    };
    query?: never;
    url: '/v2/gene/id/{gene_id}/orthogroups';
};

export type GeneOrthogroupsErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Gene not found
     */
    404: ErrorResponse;
};

export type GeneOrthogroupsError = GeneOrthogroupsErrors[keyof GeneOrthogroupsErrors];

export type GeneOrthogroupsResponses = {
    /**
     * Orthogroups containing the gene
     */
    200: Array<Orthogroup>;
};

export type GeneOrthogroupsResponse = GeneOrthogroupsResponses[keyof GeneOrthogroupsResponses];

export type GeneSearchData = {
    body?: never;
    path?: never;
    query?: {
        tax_id?: number | null;
        symbol?: string | null;
        locus_tag?: string | null;
        q?: string | null;
        limit?: number | null;
    };
    url: '/v2/gene/search';
};

export type GeneSearchResponses = {
    /**
     * Matching genes
     */
    200: Array<Gene>;
};

export type GeneSearchResponse = GeneSearchResponses[keyof GeneSearchResponses];

export type AssemblyData = {
    body?: never;
    path: {
        /**
         * Assembly accession
         */
        accession: string;
    };
    query?: never;
    url: '/v2/genome/accession/{accession}';
};

export type AssemblyErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Assembly not found
     */
    404: ErrorResponse;
};

export type AssemblyError = AssemblyErrors[keyof AssemblyErrors];

export type AssemblyResponses = {
    /**
     * Assembly metadata
     */
    200: Assembly;
};

export type AssemblyResponse = AssemblyResponses[keyof AssemblyResponses];

export type RegionFeaturesData = {
    body?: never;
    path: {
        /**
         * Assembly accession
         */
        accession: string;
        /**
         * 1-based closed region, e.g. chr1:1-100000
         */
        region: string;
    };
    query?: never;
    url: '/v2/genome/accession/{accession}/region/{region}/features';
};

export type RegionFeaturesErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Assembly not found
     */
    404: ErrorResponse;
};

export type RegionFeaturesError = RegionFeaturesErrors[keyof RegionFeaturesErrors];

export type RegionFeaturesResponses = {
    /**
     * Overlapping genes
     */
    200: Array<Gene>;
};

export type RegionFeaturesResponse = RegionFeaturesResponses[keyof RegionFeaturesResponses];

export type SequenceSegmentsData = {
    body?: never;
    path: {
        /**
         * Assembly accession
         */
        accession: string;
        /**
         * Sequence name, e.g. chr1
         */
        sequence_name: string;
    };
    query: {
        /**
         * Segment starts, 0-based inclusive. Repeat once per segment.
         */
        start: Array<number>;
        /**
         * Segment ends, 0-based exclusive. Repeat once per segment.
         */
        end: Array<number>;
        /**
         * Optional strand transform. `reverse` returns the reverse complement of the concatenated segments.
         */
        strand?: Strand;
        /**
         * Response format. Use `fasta` for sequence downloads.
         */
        format?: SequenceOutputFormat;
    };
    url: '/v2/genome/accession/{accession}/sequence/{sequence_name}';
};

export type SequenceSegmentsErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Assembly or sequence not found
     */
    404: ErrorResponse;
};

export type SequenceSegmentsError = SequenceSegmentsErrors[keyof SequenceSegmentsErrors];

export type SequenceSegmentsResponses = {
    /**
     * Concatenated sequence segments
     */
    200: string;
};

export type SequenceSegmentsResponse = SequenceSegmentsResponses[keyof SequenceSegmentsResponses];

export type AssemblySequencesData = {
    body?: never;
    path: {
        /**
         * Assembly accession
         */
        accession: string;
    };
    query?: never;
    url: '/v2/genome/accession/{accession}/sequences';
};

export type AssemblySequencesErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Assembly not found
     */
    404: ErrorResponse;
};

export type AssemblySequencesError = AssemblySequencesErrors[keyof AssemblySequencesErrors];

export type AssemblySequencesResponses = {
    /**
     * Assembly sequences
     */
    200: Array<Sequence>;
};

export type AssemblySequencesResponse = AssemblySequencesResponses[keyof AssemblySequencesResponses];

export type TaxonData = {
    body?: never;
    path: {
        /**
         * NCBI Taxonomy ID
         */
        tax_id: number;
    };
    query?: never;
    url: '/v2/genome/taxon/{tax_id}';
};

export type TaxonErrors = {
    /**
     * Taxon not found
     */
    404: ErrorResponse;
};

export type TaxonError = TaxonErrors[keyof TaxonErrors];

export type TaxonResponses = {
    /**
     * Taxon and assemblies
     */
    200: TaxonResponse;
};

export type TaxonResponse2 = TaxonResponses[keyof TaxonResponses];

export type KeggPathwayData = {
    body?: never;
    path: {
        /**
         * Canonical KEGG pathway id (e.g. map00010)
         */
        pathway_id: string;
    };
    query?: never;
    url: '/v2/kegg/pathway/{pathway_id}';
};

export type KeggPathwayErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * KEGG pathway not found
     */
    404: ErrorResponse;
};

export type KeggPathwayError = KeggPathwayErrors[keyof KeggPathwayErrors];

export type KeggPathwayResponses = {
    /**
     * KEGG pathway detail with KOs and the genes annotated with each KO
     */
    200: KeggPathwayDetail;
};

export type KeggPathwayResponse = KeggPathwayResponses[keyof KeggPathwayResponses];

export type KeggPathwaysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/kegg/pathways';
};

export type KeggPathwaysResponses = {
    /**
     * KEGG pathway catalog with dataset-level KO and gene counts
     */
    200: Array<KeggPathwaySummary>;
};

export type KeggPathwaysResponse = KeggPathwaysResponses[keyof KeggPathwaysResponses];

export type OrthogroupData = {
    body?: never;
    path: {
        /**
         * Orthogroup identifier
         */
        orthogroup_id: string;
    };
    query?: never;
    url: '/v2/orthogroup/{orthogroup_id}';
};

export type OrthogroupErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Orthogroup not found
     */
    404: ErrorResponse;
};

export type OrthogroupError = OrthogroupErrors[keyof OrthogroupErrors];

export type OrthogroupResponses = {
    /**
     * Orthogroup detail
     */
    200: Orthogroup;
};

export type OrthogroupResponse = OrthogroupResponses[keyof OrthogroupResponses];

export type CreateBlastnJobData = {
    body: BlastnJobRequest;
    path?: never;
    query?: never;
    url: '/v2/tools/blastn/jobs';
};

export type CreateBlastnJobErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * BLASTN worker is not configured
     */
    503: ErrorResponse;
};

export type CreateBlastnJobError = CreateBlastnJobErrors[keyof CreateBlastnJobErrors];

export type CreateBlastnJobResponses = {
    /**
     * BLASTN job accepted
     */
    202: BlastnJobResponse;
};

export type CreateBlastnJobResponse = CreateBlastnJobResponses[keyof CreateBlastnJobResponses];

export type BlastnJobData = {
    body?: never;
    path: {
        /**
         * BLASTN job identifier
         */
        job_id: string;
    };
    query?: never;
    url: '/v2/tools/blastn/jobs/{job_id}';
};

export type BlastnJobErrors = {
    /**
     * Job not found
     */
    404: ErrorResponse;
    /**
     * BLASTN worker is not configured
     */
    503: ErrorResponse;
};

export type BlastnJobError = BlastnJobErrors[keyof BlastnJobErrors];

export type BlastnJobResponses = {
    /**
     * BLASTN job status
     */
    200: BlastnJobResponse;
};

export type BlastnJobResponse2 = BlastnJobResponses[keyof BlastnJobResponses];

export type CreateBlastpJobData = {
    body: BlastpJobRequest;
    path?: never;
    query?: never;
    url: '/v2/tools/blastp/jobs';
};

export type CreateBlastpJobErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * BLASTP worker is not configured
     */
    503: ErrorResponse;
};

export type CreateBlastpJobError = CreateBlastpJobErrors[keyof CreateBlastpJobErrors];

export type CreateBlastpJobResponses = {
    /**
     * BLASTP job accepted
     */
    202: BlastnJobResponse;
};

export type CreateBlastpJobResponse = CreateBlastpJobResponses[keyof CreateBlastpJobResponses];

export type BlastpJobData = {
    body?: never;
    path: {
        /**
         * BLASTP job identifier
         */
        job_id: string;
    };
    query?: never;
    url: '/v2/tools/blastp/jobs/{job_id}';
};

export type BlastpJobErrors = {
    /**
     * Job not found
     */
    404: ErrorResponse;
    /**
     * BLASTP worker is not configured
     */
    503: ErrorResponse;
};

export type BlastpJobError = BlastpJobErrors[keyof BlastpJobErrors];

export type BlastpJobResponses = {
    /**
     * BLASTP job status
     */
    200: BlastnJobResponse;
};

export type BlastpJobResponse = BlastpJobResponses[keyof BlastpJobResponses];

export type TranscriptProteinData = {
    body?: never;
    path: {
        /**
         * Transcript identifier (e.g. Mp1g00010.1)
         */
        transcript_id: string;
    };
    query?: {
        /**
         * Response format. Use `fasta` for sequence downloads (default `plain`).
         */
        format?: null | SequenceOutputFormat;
    };
    url: '/v2/transcript/id/{transcript_id}/protein';
};

export type TranscriptProteinErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
    /**
     * Transcript or protein sequence not available
     */
    404: ErrorResponse;
};

export type TranscriptProteinError = TranscriptProteinErrors[keyof TranscriptProteinErrors];

export type TranscriptProteinResponses = {
    /**
     * Translated protein sequence
     */
    200: string;
};

export type TranscriptProteinResponse = TranscriptProteinResponses[keyof TranscriptProteinResponses];
