// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot';

export const vAnnotationSource = v.union([
    v.picklist(['inter_pro_scan']),
    v.picklist(['go']),
    v.picklist(['kegg']),
    v.picklist(['manual']),
    v.object({
        other: v.string()
    })
]);

export const vAnnotationEvidence = v.object({
    attributes: v.record(v.string(), v.string()),
    method: v.nullish(v.string()),
    source: vAnnotationSource
});

export const vAntibody = v.string();

/**
 * Epigenome assay supported in MVP.
 *
 * Only ChIP-seq and ATAC-seq are modelled. CUT&RUN / CUT&Tag / DNase-seq are
 * out of MVP scope; add new variants when those assays are imported.
 */
export const vAssay = v.picklist(['chip_seq', 'atac_seq']);

export const vAssemblyAccession = v.string();

export const vAssemblySource = v.picklist([
    'ncbi',
    'marpol_base',
    'tair',
    'phytozome',
    'community',
    'local'
]);

export const vBlastnJobRequest = v.object({
    assemblyAccession: v.string(),
    evalue: v.nullish(v.number()),
    maxTargetSeqs: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0))),
    query: v.string(),
    task: v.nullish(v.string())
});

export const vBlastpJobRequest = v.object({
    assemblyAccession: v.string(),
    evalue: v.nullish(v.number()),
    maxTargetSeqs: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0))),
    query: v.string(),
    task: v.nullish(v.string())
});

/**
 * One node in a flat dendrogram.
 */
export const vClusterDendrogramNode = v.object({
    distance: v.number(),
    id: v.pipe(v.number(), v.integer(), v.minValue(0)),
    leafIndex: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0))),
    left: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0))),
    right: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0))),
    size: v.pipe(v.number(), v.integer(), v.minValue(0))
});

/**
 * A flat dendrogram representation suitable for JSON APIs.
 */
export const vClusterDendrogram = v.object({
    nodes: v.array(vClusterDendrogramNode),
    root: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0)))
});

export const vEnrichmentAnnotationKind = v.picklist([
    'go_term',
    'pfam',
    'inter_pro',
    'kegg',
    'kog',
    'ncbi_fam'
]);

export const vEnrichmentAnalysisRequest = v.object({
    annotationKinds: v.nullish(v.array(vEnrichmentAnnotationKind)),
    assemblyAccession: v.string(),
    backgroundGeneIds: v.nullish(v.array(v.string())),
    geneIds: v.array(v.string()),
    limit: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0))),
    minPopulationHits: v.nullish(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')))
});

export const vEpigenomePeaksQuery = v.object({
    assay: v.nullish(vAssay),
    assemblyAccession: v.string(),
    experimentIds: v.nullish(v.string()),
    limit: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0))),
    region: v.string(),
    target: v.nullish(v.string())
});

export const vErrorResponse = v.object({
    error: v.string()
});

export const vExperimentId = v.string();

export const vExperimentListQuery = v.object({
    assay: v.nullish(vAssay),
    assemblyAccession: v.nullish(v.string()),
    limit: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0))),
    target: v.nullish(v.string())
});

/**
 * Quality-control metrics for a ChIP-seq / ATAC-seq experiment, following
 * ENCODE conventions.
 *
 * All fields are `Option` because public datasets often only report a subset.
 * Pass thresholds (for surfacing badges in the UI):
 * * FRiP ≥ 0.01 (ChIP) / ≥ 0.20 (ATAC)
 * * NSC ≥ 1.05, RSC ≥ 0.8 (ChIP cross-correlation)
 * * NRF ≥ 0.8 (library complexity)
 */
export const vExperimentQc = v.object({
    frip: v.nullish(v.number()),
    mapped_reads: v.nullish(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))),
    nrf: v.nullish(v.number()),
    nsc: v.nullish(v.number()),
    rsc: v.nullish(v.number())
});

export const vExpressionGeneLabel = v.object({
    geneId: v.string(),
    label: v.string()
});

export const vExpressionSampleLabel = v.object({
    label: v.string(),
    primaryGroup: v.nullish(v.string()),
    run: v.string()
});

/**
 * Unit in which an expression value is reported.
 *
 * The variants cover the common normalized and count-based units used by
 * downstream pipelines (Salmon, Kallisto, featureCounts, DESeq2, edgeR, ...).
 */
export const vExpressionUnit = v.picklist([
    'tpm',
    'fpkm',
    'rpkm',
    'cpm',
    'raw_count',
    'normalized_count'
]);

export const vExpressionClustergramQuery = v.object({
    assemblyAccession: v.string(),
    dropMissingGenes: v.nullish(v.boolean()),
    geneIds: v.string(),
    limit: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0))),
    runs: v.nullish(v.string()),
    unit: v.nullish(vExpressionUnit)
});

export const vExpressionClustergramResponse = v.object({
    assemblyAccession: v.string(),
    columnDendrogram: vClusterDendrogram,
    columnOrder: v.array(v.pipe(v.number(), v.integer(), v.minValue(0))),
    genes: v.array(vExpressionGeneLabel),
    rowDendrogram: vClusterDendrogram,
    rowOrder: v.array(v.pipe(v.number(), v.integer(), v.minValue(0))),
    samples: v.array(vExpressionSampleLabel),
    unit: vExpressionUnit,
    values: v.array(v.number()),
    zScores: v.array(v.number())
});

export const vGeneEpigenomeQuery = v.object({
    assay: v.nullish(vAssay),
    downstreamBp: v.optional(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))),
    limit: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0))),
    target: v.nullish(v.string()),
    upstreamBp: v.optional(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')))
});

export const vGeneExpressionPoint = v.object({
    geneId: v.string(),
    label: v.string(),
    primaryGroup: v.nullish(v.string()),
    run: v.string(),
    unit: vExpressionUnit,
    value: v.number()
});

export const vGeneExpressionQuery = v.object({
    limit: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0))),
    unit: v.nullish(vExpressionUnit)
});

export const vGeneId = v.string();

export const vGeneSearchQuery = v.object({
    limit: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0))),
    locus_tag: v.nullish(v.string()),
    q: v.nullish(v.string()),
    symbol: v.nullish(v.string()),
    tax_id: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')))
});

export const vGeoSampleAccession = v.string();

export const vGeoSeriesAccession = v.string();

export const vGoNamespace = v.picklist([
    'biological_process',
    'molecular_function',
    'cellular_component'
]);

export const vEnrichmentTerm = v.object({
    id: v.string(),
    kind: vEnrichmentAnnotationKind,
    name: v.nullish(v.string()),
    namespace: v.nullish(vGoNamespace)
});

export const vEnrichmentTermResult = v.object({
    foldEnrichment: v.nullish(v.number()),
    pValue: v.number(),
    populationHits: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    populationSize: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    qValue: v.number(),
    studyGeneIds: v.array(vGeneId),
    studyHits: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    studySize: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    term: vEnrichmentTerm
});

export const vEnrichmentAnalysisResponse = v.object({
    assemblyAccession: v.string(),
    populationSize: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    results: v.array(vEnrichmentTermResult),
    studySize: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    testedTerms: v.pipe(v.number(), v.integer(), v.minValue(0))
});

export const vGoTermId = v.string();

export const vGoTermAnnotation = v.object({
    evidence: vAnnotationEvidence,
    name: v.nullish(v.string()),
    namespace: v.nullish(vGoNamespace),
    term_id: vGoTermId
});

export const vHealthResponse = v.object({
    ok: v.boolean()
});

export const vHomologySearchMethod = v.picklist(['blastn', 'blastp']);

export const vInterProId = v.string();

export const vInterProAnnotation = v.object({
    evidence: vAnnotationEvidence,
    interpro_id: vInterProId,
    name: v.nullish(v.string())
});

export const vJBrowseConfigQuery = v.object({
    base_url: v.nullish(v.string())
});

export const vJBrowseDefaultViewInit = v.object({
    assembly: v.string(),
    loc: v.string(),
    tracks: v.array(v.string())
});

export const vJBrowseDefaultView = v.object({
    id: v.string(),
    init: vJBrowseDefaultViewInit,
    type: v.string()
});

export const vJBrowseDefaultSession = v.object({
    name: v.string(),
    view: vJBrowseDefaultView
});

export const vJBrowseFeature = v.object({
    attributes: v.record(v.string(), v.string()),
    end: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    name: v.string(),
    refName: v.string(),
    start: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    strand: v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    type: v.string(),
    uniqueId: v.string()
});

export const vJBrowseFeaturesQuery = v.object({
    end: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    ref_name: v.string(),
    start: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))
});

export const vJBrowsePortalConfig = v.object({
    assemblyAccession: v.string(),
    chromSizesUrl: v.string(),
    featuresUrl: v.string(),
    featuresUrlTemplate: v.string(),
    sequenceUrlTemplate: v.string()
});

export const vJBrowseRendering = v.object({
    type: v.string()
});

export const vJBrowseUriLocation = v.object({
    locationType: v.string(),
    uri: v.string()
});

export const vJBrowseChromSizesAdapter = v.object({
    chromSizesLocation: vJBrowseUriLocation,
    type: v.string()
});

export const vJBrowseSequenceTrack = v.object({
    adapter: vJBrowseChromSizesAdapter,
    rendering: vJBrowseRendering,
    trackId: v.string(),
    type: v.string()
});

export const vJBrowseAssembly = v.object({
    aliases: v.array(v.string()),
    name: v.string(),
    sequence: vJBrowseSequenceTrack
});

export const vJBrowseRootConfig = v.object({
    assemblies: v.array(vJBrowseAssembly),
    defaultSession: vJBrowseDefaultSession,
    plantGenomePortal: vJBrowsePortalConfig,
    tracks: v.array(v.record(v.string(), v.unknown()))
});

export const vJobStatusResponse = v.picklist([
    'queued',
    'running',
    'succeeded',
    'failed'
]);

export const vKeggEntryId = v.string();

export const vKeggEntryKind = v.picklist([
    'orthology',
    'pathway',
    'module',
    'reaction',
    'compound',
    'glycan',
    'other'
]);

export const vKeggAnnotation = v.object({
    entry_id: vKeggEntryId,
    entry_kind: vKeggEntryKind,
    evidence: vAnnotationEvidence,
    name: v.nullish(v.string())
});

export const vKeggGeneSummary = v.object({
    id: vGeneId,
    locus_tag: v.nullish(v.string()),
    symbol: v.nullish(v.string())
});

export const vKeggModuleId = v.string();

export const vKeggModule = v.object({
    id: vKeggModuleId,
    name: v.nullish(v.string())
});

export const vKeggPathwayId = v.string();

export const vKeggPathway = v.object({
    id: vKeggPathwayId,
    name: v.nullish(v.string())
});

export const vKeggPathwayKoEntry = v.object({
    genes: v.array(vKeggGeneSummary),
    ko: vKeggEntryId
});

export const vKeggPathwayDetail = v.object({
    kos: v.array(vKeggPathwayKoEntry),
    pathway: vKeggPathway
});

export const vKeggPathwaySummary = v.object({
    gene_count: v.pipe(v.number(), v.integer(), v.minValue(0)),
    ko_count: v.pipe(v.number(), v.integer(), v.minValue(0)),
    pathway: vKeggPathway
});

export const vKeggReactionId = v.string();

export const vKeggKoLinks = v.object({
    ko: vKeggEntryId,
    modules: v.array(vKeggModuleId),
    pathways: v.array(vKeggPathwayId),
    reactions: v.array(vKeggReactionId)
});

export const vKeggReaction = v.object({
    id: vKeggReactionId,
    name: v.nullish(v.string())
});

export const vGeneKeggOrthologyEntry = v.object({
    ko: vKeggEntryId,
    modules: v.array(vKeggModule),
    name: v.nullish(v.string()),
    pathways: v.array(vKeggPathway),
    reactions: v.array(vKeggReaction)
});

export const vGeneKeggView = v.object({
    entries: v.array(vGeneKeggOrthologyEntry),
    gene_id: vGeneId
});

export const vKeggCatalog = v.object({
    ko_links: v.optional(v.array(vKeggKoLinks)),
    modules: v.optional(v.array(vKeggModule)),
    pathways: v.optional(v.array(vKeggPathway)),
    reactions: v.optional(v.array(vKeggReaction))
});

export const vKogEntryId = v.string();

export const vKogAnnotation = v.object({
    entry_id: vKogEntryId,
    evidence: vAnnotationEvidence,
    interpro_id: v.nullish(vInterProId),
    name: v.nullish(v.string())
});

export const vNcbiFamAccession = v.string();

export const vNcbiFamAnnotation = v.object({
    accession: vNcbiFamAccession,
    evidence: vAnnotationEvidence,
    interpro_id: v.nullish(vInterProId),
    name: v.nullish(v.string())
});

export const vOrthogroupId = v.string();

/**
 * Whether a peak file is narrowPeak (BED6+4, has summit offset) or broadPeak
 * (BED6+3, no summit).
 *
 * Histone marks form broad domains (H3K27me3, H3K9me3, H3K36me3) and are
 * usually called with `--broad`; sharp marks (H3K4me3, H3K27ac) and
 * transcription factors give narrow peaks. ATAC-seq peaks are narrow.
 */
export const vPeakKind = v.picklist(['narrow', 'broad']);

export const vEpigenomeExperimentSummary = v.object({
    assay: vAssay,
    devStage: v.nullish(v.string()),
    experimentId: v.string(),
    frip: v.nullish(v.number()),
    peakKind: vPeakKind,
    replicate: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
    signalUrl: v.nullish(v.string()),
    target: v.nullish(v.string()),
    tissue: v.nullish(v.string()),
    treatment: v.nullish(v.string())
});

export const vPfamAccession = v.string();

export const vPfamAnnotation = v.object({
    accession: vPfamAccession,
    evidence: vAnnotationEvidence,
    interpro_id: v.nullish(vInterProId),
    name: v.nullish(v.string())
});

export const vFunctionalAnnotation = v.union([
    v.intersect([vInterProAnnotation, v.object({
            kind: v.picklist(['inter_pro'])
        })]),
    v.intersect([vPfamAnnotation, v.object({
            kind: v.picklist(['pfam'])
        })]),
    v.intersect([vNcbiFamAnnotation, v.object({
            kind: v.picklist(['ncbi_fam'])
        })]),
    v.intersect([vKogAnnotation, v.object({
            kind: v.picklist(['kog'])
        })]),
    v.intersect([vGoTermAnnotation, v.object({
            kind: v.picklist(['go_term'])
        })]),
    v.intersect([vKeggAnnotation, v.object({
            kind: v.picklist(['kegg'])
        })])
]);

export const vPosition0 = v.pipe(v.union([
    v.number(),
    v.string(),
    v.bigint()
]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'));

export const vPosition1 = v.pipe(v.union([
    v.number(),
    v.string(),
    v.bigint()
]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'));

export const vPublicRegion = v.object({
    end: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    sequenceName: v.string(),
    start: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))
});

export const vRefgetQuery = v.object({
    end: v.nullish(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))),
    start: v.nullish(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')))
});

export const vRefgetServiceInfo = v.object({
    circular_supported: v.boolean(),
    id: v.string(),
    name: v.string(),
    subsequence_limit: v.nullish(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')))
});

export const vSequenceName = v.string();

export const vClosedRegion = v.object({
    end: vPosition1,
    sequence_name: vSequenceName,
    start: vPosition1
});

export const vHalfOpenRegion = v.object({
    end: vPosition0,
    sequence_name: vSequenceName,
    start: vPosition0
});

export const vSequence = v.object({
    assembly_accession: vAssemblyAccession,
    length: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    name: vSequenceName,
    refget_checksum: v.string()
});

export const vSequenceOutputFormat = v.picklist(['plain', 'fasta']);

export const vProteinQuery = v.object({
    format: v.nullish(vSequenceOutputFormat)
});

export const vSraRunAccession = v.string();

export const vStrand = v.picklist([
    'forward',
    'reverse',
    'unknown'
]);

export const vGene = v.object({
    annotations: v.array(vFunctionalAnnotation),
    assembly_accession: vAssemblyAccession,
    attributes: v.record(v.string(), v.string()),
    feature_type: v.string(),
    id: vGeneId,
    locus_tag: v.nullish(v.string()),
    region: vHalfOpenRegion,
    sequence_name: vSequenceName,
    strand: vStrand,
    symbol: v.nullish(v.string())
});

export const vHomologyHit = v.object({
    alignmentLength: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    assemblyAccession: vAssemblyAccession,
    bitScore: v.number(),
    evalue: v.number(),
    gapOpens: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    mismatches: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    percentIdentity: v.number(),
    queryAlignment: v.string(),
    queryEnd: vPosition1,
    queryId: v.string(),
    queryStart: vPosition1,
    sequenceName: vSequenceName,
    strand: vStrand,
    subjectAlignment: v.string(),
    subjectEnd: vPosition1,
    subjectRegion: vClosedRegion,
    subjectStart: vPosition1
});

export const vAnnotatedHomologyHitResponse = v.object({
    hit: vHomologyHit,
    overlappingGeneIds: v.array(vGeneId)
});

export const vAnnotatedHomologySearchResultResponse = v.object({
    hits: v.array(vAnnotatedHomologyHitResponse),
    method: vHomologySearchMethod,
    task: v.string()
});

export const vBlastnJobResponse = v.object({
    error: v.nullish(v.string()),
    id: v.string(),
    kind: v.string(),
    result: v.nullish(vAnnotatedHomologySearchResultResponse),
    status: vJobStatusResponse
});

/**
 * One peak call (narrowPeak or broadPeak row), normalised to the portal's
 * internal 0-based half-open coordinate system.
 *
 * `summit_offset` is `Some` for narrowPeak (column 10, summit offset from
 * `region.start`) and `None` for broadPeak.
 */
export const vPeak = v.object({
    name: v.string(),
    p_value: v.number(),
    q_value: v.number(),
    region: vHalfOpenRegion,
    score: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    signal_value: v.number(),
    strand: vStrand,
    summit_offset: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')))
});

/**
 * A peak emitted on the public API: coordinates are re-projected to 1-based
 * closed form so the wire shape matches the portal's other region payloads.
 */
export const vPublicPeak = v.object({
    end: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    name: v.string(),
    pValue: v.number(),
    qValue: v.number(),
    score: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    sequenceName: v.string(),
    signalValue: v.number(),
    start: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    strand: vStrand,
    summitOffset: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')))
});

export const vEpigenomeExperimentWithPeaks = v.object({
    experiment: vEpigenomeExperimentSummary,
    peaks: v.array(vPublicPeak)
});

export const vEpigenomeGeneView = v.object({
    assemblyAccession: v.string(),
    experiments: v.array(vEpigenomeExperimentWithPeaks),
    geneId: v.string(),
    region: vPublicRegion
});

export const vEpigenomePeakHit = v.object({
    experimentId: v.string(),
    peak: vPublicPeak
});

export const vSequenceSegmentsQuery = v.object({
    end: v.array(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))),
    format: v.nullish(vSequenceOutputFormat),
    start: v.array(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))),
    strand: v.nullish(vStrand)
});

export const vTarget = v.string();

/**
 * One ChIP-seq or ATAC-seq experiment.
 *
 * "Experiment" here means *one peak-called dataset* — usually one biological
 * replicate that has been aligned and processed end-to-end. Replicates are
 * kept as separate `Experiment`s rather than merged; this mirrors how
 * ChIP-Atlas / ENCODE expose data and lets users see per-replicate QC.
 */
export const vExperiment = v.object({
    antibody: v.nullish(vAntibody),
    assay: vAssay,
    assembly_accession: vAssemblyAccession,
    attributes: v.optional(v.record(v.string(), v.string())),
    dev_stage: v.nullish(v.string()),
    geo_sample: v.nullish(vGeoSampleAccession),
    geo_series: v.nullish(vGeoSeriesAccession),
    id: vExperimentId,
    peak_kind: vPeakKind,
    pipeline: v.nullish(v.string()),
    qc: v.optional(vExperimentQc),
    qvalue_cutoff: v.nullish(v.number()),
    replicate: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
    signal_file: v.nullish(v.string()),
    sra_runs: v.optional(v.array(vSraRunAccession)),
    target: v.nullish(vTarget),
    tissue: v.nullish(v.string()),
    treatment: v.nullish(v.string())
});

export const vEpigenomeExperimentDetail = v.object({
    experiment: vExperiment,
    peakCount: v.pipe(v.number(), v.integer(), v.minValue(0)),
    signalUrl: v.nullish(v.string())
});

export const vTaxId = v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'));

export const vAssembly = v.object({
    accession: vAssemblyAccession,
    name: v.string(),
    refget_checksum: v.nullish(v.string()),
    source: vAssemblySource,
    tax_id: vTaxId
});

export const vOrthogroupMember = v.object({
    assembly_accession: v.nullish(vAssemblyAccession),
    gene_id: vGeneId,
    scientific_name: v.string(),
    symbol: v.nullish(v.string()),
    tax_id: vTaxId
});

export const vOrthogroup = v.object({
    id: vOrthogroupId,
    members: v.array(vOrthogroupMember)
});

export const vOrthogroupCatalog = v.object({
    groups: v.array(vOrthogroup)
});

export const vTaxon = v.object({
    common_name: v.nullish(v.string()),
    rank: v.string(),
    scientific_name: v.string(),
    tax_id: vTaxId
});

export const vTaxonResponse = v.object({
    assemblies: v.array(vAssembly),
    taxon: vTaxon
});

export const vTranscriptId = v.string();

export const vCds = v.object({
    phase: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
    region: vHalfOpenRegion,
    sequence_name: vSequenceName,
    strand: vStrand,
    transcript_id: vTranscriptId
});

export const vExon = v.object({
    region: vHalfOpenRegion,
    sequence_name: vSequenceName,
    strand: vStrand,
    transcript_id: vTranscriptId
});

export const vTranscript = v.object({
    annotations: v.array(vFunctionalAnnotation),
    attributes: v.record(v.string(), v.string()),
    feature_type: v.string(),
    gene_id: vGeneId,
    id: vTranscriptId,
    protein_checksum: v.nullish(v.string()),
    protein_length: v.nullish(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))),
    region: vHalfOpenRegion,
    sequence_name: vSequenceName,
    strand: vStrand
});

export const vGeneRecord = v.object({
    cdss: v.array(vCds),
    exons: v.array(vExon),
    gene: vGene,
    transcripts: v.array(vTranscript)
});

/**
 * Health check
 */
export const vHealthResponse2 = vHealthResponse;

export const vJbrowseChromSizesPath = v.object({
    accession: v.string()
});

/**
 * UCSC chrom.sizes compatible sequence sizes
 */
export const vJbrowseChromSizesResponse = v.string();

export const vJbrowseFeaturesPath = v.object({
    accession: v.string()
});

export const vJbrowseFeaturesQuery = v.object({
    ref_name: v.string(),
    start: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    end: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))
});

/**
 * Features for a JBrowse custom adapter
 */
export const vJbrowseFeaturesResponse = v.array(vJBrowseFeature);

export const vJbrowseDefaultConfigQuery = v.object({
    base_url: v.nullish(v.string())
});

/**
 * Default JBrowse launch config
 */
export const vJbrowseDefaultConfigResponse = vJBrowseRootConfig;

export const vJbrowseConfigPath = v.object({
    accession: v.string()
});

export const vJbrowseConfigQuery = v.object({
    base_url: v.nullish(v.string())
});

/**
 * JBrowse launch config
 */
export const vJbrowseConfigResponse = vJBrowseRootConfig;

/**
 * refget service info
 */
export const vRefgetServiceInfoResponse = vRefgetServiceInfo;

export const vRefgetSequencePath = v.object({
    checksum: v.string()
});

export const vRefgetSequenceQuery = v.object({
    start: v.nullish(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))),
    end: v.nullish(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')))
});

/**
 * Reference sequence
 */
export const vRefgetSequenceResponse = v.string();

export const vEnrichmentAnalysisBody = vEnrichmentAnalysisRequest;

/**
 * Functional annotation over-representation analysis
 */
export const vEnrichmentAnalysisResponse2 = vEnrichmentAnalysisResponse;

export const vEpigenomeExperimentPath = v.object({
    experiment_id: v.string()
});

/**
 * Experiment metadata + QC + signal URL
 */
export const vEpigenomeExperimentResponse = vEpigenomeExperimentDetail;

export const vEpigenomeExperimentsQuery = v.object({
    assemblyAccession: v.nullish(v.string()),
    assay: v.nullish(vAssay),
    target: v.nullish(v.string()),
    limit: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0)))
});

/**
 * Epigenome experiments matching the filters
 */
export const vEpigenomeExperimentsResponse = v.array(vEpigenomeExperimentSummary);

export const vEpigenomePeaksQuery2 = v.object({
    assemblyAccession: v.string(),
    region: v.string(),
    experimentIds: v.nullish(v.string()),
    assay: v.nullish(vAssay),
    target: v.nullish(v.string()),
    limit: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0)))
});

/**
 * Peaks overlapping the region
 */
export const vEpigenomePeaksResponse = v.array(vEpigenomePeakHit);

export const vExpressionClustergramQuery2 = v.object({
    assemblyAccession: v.string(),
    geneIds: v.string(),
    unit: v.nullish(vExpressionUnit),
    runs: v.nullish(v.string()),
    limit: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0))),
    dropMissingGenes: v.nullish(v.boolean())
});

/**
 * Expression matrix with Rust-computed cluster ordering
 */
export const vExpressionClustergramResponse2 = vExpressionClustergramResponse;

export const vGenePath = v.object({
    gene_id: v.string()
});

/**
 * Gene detail
 */
export const vGeneResponse = vGeneRecord;

export const vGeneEpigenomePath = v.object({
    gene_id: v.string()
});

export const vGeneEpigenomeQuery2 = v.object({
    upstreamBp: v.optional(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))),
    downstreamBp: v.optional(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))),
    assay: v.nullish(vAssay),
    target: v.nullish(v.string()),
    limit: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0)))
});

/**
 * Experiments with peaks overlapping the gene body + flanks
 */
export const vGeneEpigenomeResponse = vEpigenomeGeneView;

export const vGeneExpressionPath = v.object({
    gene_id: v.string()
});

export const vGeneExpressionQuery2 = v.object({
    unit: v.nullish(vExpressionUnit),
    limit: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0)))
});

/**
 * Expression values for one gene
 */
export const vGeneExpressionResponse = v.array(vGeneExpressionPoint);

export const vGeneKeggPath = v.object({
    gene_id: v.string()
});

/**
 * Per-gene KEGG view with KOs hydrated by their related pathways/modules/reactions
 */
export const vGeneKeggResponse = vGeneKeggView;

export const vGeneOrthogroupsPath = v.object({
    gene_id: v.string()
});

/**
 * Orthogroups containing the gene
 */
export const vGeneOrthogroupsResponse = v.array(vOrthogroup);

export const vGeneSearchQuery2 = v.object({
    tax_id: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
    symbol: v.nullish(v.string()),
    locus_tag: v.nullish(v.string()),
    q: v.nullish(v.string()),
    limit: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(0)))
});

/**
 * Matching genes
 */
export const vGeneSearchResponse = v.array(vGene);

export const vAssemblyPath = v.object({
    accession: v.string()
});

/**
 * Assembly metadata
 */
export const vAssemblyResponse = vAssembly;

export const vRegionFeaturesPath = v.object({
    accession: v.string(),
    region: v.string()
});

/**
 * Overlapping genes
 */
export const vRegionFeaturesResponse = v.array(vGene);

export const vSequenceSegmentsPath = v.object({
    accession: v.string(),
    sequence_name: v.string()
});

export const vSequenceSegmentsQuery2 = v.object({
    start: v.array(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))),
    end: v.array(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt(0)), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))),
    strand: v.optional(vStrand),
    format: v.optional(vSequenceOutputFormat)
});

/**
 * Concatenated sequence segments
 */
export const vSequenceSegmentsResponse = v.string();

export const vAssemblySequencesPath = v.object({
    accession: v.string()
});

/**
 * Assembly sequences
 */
export const vAssemblySequencesResponse = v.array(vSequence);

export const vTaxonPath = v.object({
    tax_id: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))
});

/**
 * Taxon and assemblies
 */
export const vTaxonResponse2 = vTaxonResponse;

export const vKeggPathwayPath = v.object({
    pathway_id: v.string()
});

/**
 * KEGG pathway detail with KOs and the genes annotated with each KO
 */
export const vKeggPathwayResponse = vKeggPathwayDetail;

/**
 * KEGG pathway catalog with dataset-level KO and gene counts
 */
export const vKeggPathwaysResponse = v.array(vKeggPathwaySummary);

export const vOrthogroupPath = v.object({
    orthogroup_id: v.string()
});

/**
 * Orthogroup detail
 */
export const vOrthogroupResponse = vOrthogroup;

export const vCreateBlastnJobBody = vBlastnJobRequest;

/**
 * BLASTN job accepted
 */
export const vCreateBlastnJobResponse = vBlastnJobResponse;

export const vBlastnJobPath = v.object({
    job_id: v.string()
});

/**
 * BLASTN job status
 */
export const vBlastnJobResponse2 = vBlastnJobResponse;

export const vCreateBlastpJobBody = vBlastpJobRequest;

/**
 * BLASTP job accepted
 */
export const vCreateBlastpJobResponse = vBlastnJobResponse;

export const vBlastpJobPath = v.object({
    job_id: v.string()
});

/**
 * BLASTP job status
 */
export const vBlastpJobResponse = vBlastnJobResponse;

export const vTranscriptProteinPath = v.object({
    transcript_id: v.string()
});

export const vTranscriptProteinQuery = v.object({
    format: v.nullish(vSequenceOutputFormat)
});

/**
 * Translated protein sequence
 */
export const vTranscriptProteinResponse = v.string();
