import { defineConfig } from "oxlint";

export default defineConfig({
  categories: {
    correctness: "error",
    nursery: "error",
    pedantic: "error",
    perf: "error",
    restriction: "error",
    style: "error",
    suspicious: "error",
  },
  env: {
    browser: true,
    es2022: true,
  },
  ignorePatterns: ["dist", "coverage", "node_modules", "src/api/client"],
  options: {
    denyWarnings: true,
    maxWarnings: 0,
    reportUnusedDisableDirectives: "error",
    respectEslintDisableDirectives: true,
  },
  overrides: [
    {
      env: {
        node: true,
      },
      files: ["*.config.ts", "vite.config.ts", "vitest.config.ts", "oxlint.config.ts"],
      rules: {
        "import/no-default-export": "off",
        "import/no-nodejs-modules": "off",
        "import/no-unassigned-import": "off",
        "no-magic-numbers": "off",
        "node/no-process-env": "off",
        "unicorn/filename-case": "off",
        "unicorn/prefer-module": "off",
      },
    },
    {
      env: {
        browser: true,
        es2022: true,
        vitest: true,
      },
      files: ["**/*.test.ts", "**/*.test.tsx", "**/*.spec.ts", "**/*.spec.tsx"],
      plugins: [
        "eslint",
        "typescript",
        "oxc",
        "unicorn",
        "import",
        "react",
        "react-perf",
        "jsx-a11y",
        "vitest",
        "promise",
      ],
      rules: {
        "max-lines-per-function": "off",
        "no-magic-numbers": "off",
        "vitest/expect-expect": "error",
        "vitest/no-disabled-tests": "error",
        "vitest/no-focused-tests": "error",
        "vitest/prefer-expect-assertions": "error",
      },
    },
    {
      files: ["src/**/*.tsx", "src/**/*.ts"],
      rules: {
        "no-undefined": "off",
        "react/no-multi-comp": "off",
      },
    },
    {
      files: ["src/components/**/*.tsx"],
      rules: {
        "react/no-multi-comp": "error",
      },
    },
  ],
  plugins: [
    "eslint",
    "typescript",
    "oxc",
    "unicorn",
    "import",
    "react",
    "react-perf",
    "jsx-a11y",
    "promise",
  ],
  rules: {
    eqeqeq: ["error", "always"],
    "import/consistent-type-specifier-style": "off",
    "import/no-default-export": "off",
    "import/no-duplicates": "error",
    "import/no-mutable-exports": "error",
    "import/no-unassigned-import": ["error", { allow: ["**/*.css"] }],
    "no-console": "error",
    "no-debugger": "error",
    "no-duplicate-imports": "off",
    "no-restricted-globals": ["error", "event", "fdescribe", "fit"],
    "oxc/no-async-await": "off",
    "prefer-const": ["error", { destructuring: "all" }],
    "react/jsx-boolean-value": ["error", "never"],
    "react/jsx-curly-brace-presence": [
      "error",
      { children: "never", propElementValues: "always", props: "never" },
    ],
    "react/jsx-filename-extension": ["error", { extensions: [".tsx"] }],
    "react/jsx-no-constructed-context-values": "error",
    "react/jsx-no-useless-fragment": "error",
    "react/no-array-index-key": "error",
    "react/no-danger": "error",
    "react/no-multi-comp": "error",
    "react/no-unstable-nested-components": "error",
    "react/only-export-components": "error",
    "react/react-in-jsx-scope": "off",
    "react/self-closing-comp": ["error", { component: true, html: true }],
    "sort-imports": "off",
    "typescript/array-type": ["error", { default: "array-simple" }],
    "typescript/ban-ts-comment": "error",
    "typescript/consistent-type-definitions": ["error", "type"],
    "typescript/consistent-type-imports": [
      "error",
      { fixStyle: "inline-type-imports", prefer: "type-imports" },
    ],
    "typescript/no-explicit-any": "error",
    "typescript/no-non-null-assertion": "error",
    "typescript/no-unnecessary-type-assertion": "error",
    "typescript/prefer-nullish-coalescing": "error",
    "typescript/prefer-optional-chain": "error",
    "unicorn/filename-case": ["error", { cases: { camelCase: true, pascalCase: true } }],
    "unicorn/no-null": "error",
    "unicorn/prefer-dom-node-text-content": "error",
    "unicorn/prefer-query-selector": "error",
  },
  settings: {
    "jsx-a11y": {
      components: {
        Button: "button",
      },
    },
    react: {
      linkComponents: [{ linkAttribute: "to", name: "NavLink" }],
      version: "19.2.6",
    },
    vitest: {
      typecheck: true,
    },
  },
});
